apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: adharshregistry.azurecr.io/civic-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              value:  "http://4.187.136.178:5000"
          volumeMounts:
            - name: frontend-nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: frontend-nginx-config
          configMap:
            name: frontend-nginx-config