apiVersion: v1
kind: Service
metadata:
  name: {{ include "civic-app.backendServiceName" . }}
  labels:
    {{- include "civic-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "civic-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
